### PR TITLE
stop holding polymer wrong

### PR DESCRIPTION
**Pull request by notwaldorf**
Otherwise you spend an hour thinking Polymer is broken (it isn't) and filing: https://github.com/Polymer/polymer/issues/2426 (and then insta closing it because you're the problem)

TL: DR: `Polymer.dom`.

### CODE REVIEW

**Comment by samccone** [comment]
👍👍👍👍👍👏🐴🙇✈️🐰🚜🐐🐐🐐🐐🐐🐐

**Comment by ebidel** [comment]
@notwaldorf I also had luck with `scopeSubtree` in the `highlightjs-element`. It's great for stuff like this where the 3rd party lib doesn't know about shady dom. Help em out, ya know!

https://github.com/Polymer/highlightjs-element/commit/6769356150c8a099edba00ae937b68ab37e13970

**Comment by addyosmani** [comment]
LGTM2.

**Comment by notwaldorf** [comment]
@ebidel but in this case, my div should know about `Polymer.dom` since I've created it, right? (it's either a light child or a shadow child)

**Pull request merged**
