### PR TITLE
fix webpack support

### LINKED ISSUE #96: Webpack support broken
Issue with webpack using @polymer/iron-demo-helpers/demo-snippet on version 3.0.0-pre.23:
```
Uncaught ReferenceError: marked is not defined
    at HTMLElement.render (marked-element.js:298)
```

I think this has been fixed in https://github.com/PolymerElements/marked-element/issues/81 and then broke again.

`&& window.require` has been added here https://github.com/PolymerElements/marked-element/commit/1fef15da17555cb91f1b18fed1aa7666ba3ebda9#diff-b3e973a07f826cf78314752a8b5a4cfcR13
If I revert that line to `if (!window.marked) {`, it fixes the bug, but I don't understand why `&& window.require` has been added.

### PR DESCRIPTION
**Pull request by e111077**
fixes #96

### CODE REVIEW

**Comment by bicknellr** [comment]
I think this should also change `'../../marked/lib/marked.js'` -> `'marked/lib/marked.js'`. Is there a reason it's being referenced by path?

**Comment by bicknellr** [comment]
Just talked with @justinfagnani, he had an idea that looks like it would work well here:

```js
import * as marked from 'marked/lib/marked.js';
if (!window.marked) {
  window.marked = marked;
}
```

This way, if marked is loaded by the browser, it will add `window.marked`, but if you use webpack to convert your modules to a single bundle, webpack makes `import * as marked from ...` turn `marked` into whatever was assigned to `module.exports`, which is what `window.marked` would otherwise be.

---

https://github.com/webpack/webpack/issues/706 has some extra context about how webpack handles `module.exports = ...`.

**Comment by e111077** [comment]
@aomarks TS is failing in Travis. Is there some way we can ignore this "implicit any type" error?

**Comment by bicknellr** [comment]
It looks like `@types/marked` exists, so I tried installing it but it didn't seem to change anything; I'm not really sure how TypeScript decides where to look for types, though. Also, I tried removing `gen-tsd.json`, which seems to exclude types for marked (?), but this didn't have any effect either.

**Comment by e111077** [comment]
You'd need to define that in a tsconfig.json, which I assume is supplied by the gen-ts-types lib

**Comment by e111077** [comment]
all green now

**Pull request merged**
