### PR TITLE
add `sanitizer` option.

### PR DESCRIPTION
**Pull request by howking**
undocumented chjj/marked#468, but useful option.

### CODE REVIEW

**Comment by howking** [comment]
I signed it!

**Comment by howking** [comment]
This is sample for use.
https://github.com/howking/sanitize-element
```html
<sanitize-element config='{
  "elements":["a","img"],
  "attributes":{"a":["href","title"],"img":["src"]},
  "protocols":{"a":{"href":["http","https"]}}
  }' sanitizer="{{sanitizer}}"></sanitize-element>

<marked-element markdown="[[markdown]]" sanitize sanitizer="[[sanitizer]]">
```

**Comment by stramel** [comment]
I'm good with allowing this pass-through but it should have tests supporting it and a better description of the property.

Would be good to get @e111077's input too.

**Comment by howking** [comment]
thanks !
I added tests and desc.

**Comment by e111077** [comment]
I gotta say; I really love this feature! Thanks a lot for the submission, @howking!

**Review by e111077 — APPROVED** [review]

**Comment by stramel** [comment]
:tada: thanks @howking! Released with 2.3.0

**Pull request merged**
